# Generated by Django 4.1.13 on 2024-06-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_info_id', models.IntegerField(unique=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('source', models.TextField()),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('nlp_id', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'collection1',
            },
        ),
    ]
