# Generated by Django 4.1.13 on 2024-06-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_docgeneralinfo_delete_generalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docgeneralinfo',
            name='general_info_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='docgeneralinfo',
            name='nlp_id',
            field=models.IntegerField(unique=True),
        ),
    ]
