# Generated by Django 4.1.13 on 2024-06-25 15:07

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_docgeneralinfo_delete_generalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NlpAnalysis',
            fields=[
                ('nlp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.docgeneralinfo', to_field='nlp_id')),
                ('document_type', models.CharField(max_length=100)),
                ('keywords', djongo.models.fields.JSONField()),
                ('summary', models.TextField()),
                ('document_date', models.DateField()),
                ('category', models.CharField(choices=[('Legal', 'Legal'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare')], max_length=100)),
                ('related_documents', djongo.models.fields.JSONField()),
                ('language', models.CharField(choices=[('English', 'English'), ('French', 'French'), ('Spanish', 'Spanish')], max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('confidentiality_level', models.CharField(choices=[('Public', 'Public'), ('Confidential', 'Confidential'), ('Secret', 'Secret')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('references', djongo.models.fields.JSONField()),
                ('uploaded_by', models.CharField(max_length=100)),
                ('related_projects', djongo.models.fields.JSONField()),
            ],
            options={
                'db_table': 'nlp_analysis',
            },
        ),
        migrations.AlterField(
            model_name='docgeneralinfo',
            name='general_info_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='docgeneralinfo',
            name='nlp_id',
            field=models.IntegerField(unique=True),
        ),
    ]
