# Generated by Django 4.1.13 on 2024-06-30 17:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_nlpanalysis_alter_docgeneralinfo_general_info_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryDocumentCount",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("category", models.CharField(max_length=100, unique=True)),
                ("document_count", models.IntegerField()),
            ],
            options={
                "db_table": "category_document_count",
            },
        ),
        migrations.RenameField(
            model_name="nlpanalysis",
            old_name="keywords",
            new_name="in_text_citations",
        ),
        migrations.RenameField(
            model_name="nlpanalysis",
            old_name="related_documents",
            new_name="ner",
        ),
        migrations.RemoveField(
            model_name="docgeneralinfo",
            name="id",
        ),
        migrations.RemoveField(
            model_name="nlpanalysis",
            name="document_date",
        ),
        migrations.RemoveField(
            model_name="nlpanalysis",
            name="related_projects",
        ),
        migrations.RemoveField(
            model_name="nlpanalysis",
            name="uploaded_by",
        ),
        migrations.RemoveField(
            model_name="nlpanalysis",
            name="version",
        ),
        migrations.AddField(
            model_name="docgeneralinfo",
            name="_id",
            field=djongo.models.fields.ObjectIdField(
                auto_created=True,
                default=django.utils.timezone.now,
                primary_key=True,
                serialize=False,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nlpanalysis",
            name="_id",
            field=djongo.models.fields.ObjectIdField(
                auto_created=True,
                default=django.utils.timezone.now,
                primary_key=True,
                serialize=False,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nlpanalysis",
            name="word_count",
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="nlpanalysis",
            name="category",
            field=models.CharField(
                choices=[
                    ("Contract", "Contract"),
                    ("Technology", "Technology"),
                    ("Politics", "Politics"),
                    ("Court Case", "Business"),
                    ("Agreement", "Agreement"),
                    ("Sport", "Sport"),
                    ("Business", "Business"),
                    ("Other", "Other"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="nlpanalysis",
            name="confidentiality_level",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="nlpanalysis",
            name="language",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="nlpanalysis",
            name="location",
            field=djongo.models.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name="nlpanalysis",
            name="nlp_id",
            field=models.OneToOneField(
                db_column="nlp_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.docgeneralinfo",
                to_field="nlp_id",
            ),
        ),
    ]
